#!/bin/bash

input="./filelist"

function put() {
        echo "Copying $1"
        cp "$1" ~
}

function get() {
        echo "Grabbing $1 from home"
        cp ~/"$1" .
}

function remove() {
        echo "Removing ~/$1"
        rm -f ~/"$1"
}


case $1 in

        put)
                method=put
        ;;
        get)
                method=get
        ;;
        remove)
                method=remove
        ;;
        *)
                echo "get put and remove are the only valid pass values"
                exit 0
        ;;
esac


while IFS= read -r line
do
        $method $line
done < "$input"

